### ISSUE TITLE
[Suggestion] Support for other keyboard layout

### ISSUE THREAD

**Issue by thecatcore** [Einjerjar/keymap#1]

**Comment by Einjerjar** [comment]
Oh right, totally forgot about that, will try working on it soon, thanks for the heads up

**Comment by Einjerjar** [comment]
update: latest commits now kinda allow for this, unfortunately, it is still in its early phase and currently requires lots of manual work on the player's side.

**Comment by thecatcore** [comment]
Isn't there a way to know what character is mapped to which key code on the os??

**Comment by thecatcore** [comment]
Vanilla fixed the issue while switching to LWJGL 3 in 1.13 🤔.

**Comment by Einjerjar** [comment]
yes and no, see if you have the specific keyboard layout, you can easily track down the keycodes per key, unfortunately, it seems like the keycodes are bound to the keyboard's internal layout rather than the selected kb locale from the OS, which means, even if I change my kb layout, it will still return the original keycodes for my kb, so until I figure out how I can try out different layout without changing kb, I might not be able to solve this properly.

That said, the keybinding part of the mod still works regardless of the kb layout, just that the visual keymapper won't show the proper layout for the current kb locale.

EDIT: After messing w/ windows on-screen kb, it seems like the keycodes might still be the same regardless of locale, just on a different layout, in which case, I might be able to do something soon.

**Comment by Einjerjar** [comment]
working on smth rn, no ETA but next release should finally address this issue
