### ISSUE TITLE
Crash Log (Detailed)

### ISSUE THREAD

**Issue by ardissaps** [Einjerjar/keymap#20]
Detailed all log in there : (version etc all there)(scroll to very bottom first)
https://paste.atlauncher.com/view/85cd0d2d-e938-4794-a975-316505bb3db8

**Comment by Einjerjar** [comment]
Hey there! I've looked through your logs, and as far as I've seen, this does not seem to have been caused by keymap, I'd love to hear why you think keymap might have caused the issue, and see if we can figure out something, thanks!

Edit: you might also want to check out the latest build (0.6.0) and see if that helps

Edit2: If you think it's because of `Reference map 'keymap-fabric-refmap.json' for keymap.mixins.json could not be read. If this is a development environment you can ignore this message`, then you can ignore that one, as it doesn't cause any issue (there isn't any mixin on that specific file)

**Comment by ardissaps** [comment]
Problem is Game crash with Keymap installed, when I remove Keymap game load as normal Quilt Loader 1.19.
https://paste.atlauncher.com/view/b3542cfa-057d-4a69-9ffd-7f79bd7ddf32

My 1.18.2 works fine, only crash with 1.19 Quilt (Keymap 0.6 latest)

**Comment by Einjerjar** [comment]
Thanks for the info! I guess it might indeed be keymap, I think this might be due to the fact that that I close the filesystem for reading jars after using it (to avoid leaks), which quilt ends up trying to access (after its been closed), I'll try and whip up a test environment for quilt later, hopefully have it fixed for the next update!

**Comment by ardissaps** [comment]
will that commit released? @Einjerjar

**Comment by Einjerjar** [comment]
hey there, I'm sorry for the lack of updates, I might not be able to work on the project as much as I did back then, being swamped with stuff IRL, that said, you can use this temporary build of the 1.19 branch if you're looking to use the mod for quilt, as far as my testing goes, this should work fine now.

[https://app.circleci.com/pipelines/github/Einjerjar/keymap/28/workflows/e3433aea-52d7-40a5-b8cf-dc56eae0c353/jobs/30/artifacts](https://app.circleci.com/pipelines/github/Einjerjar/keymap/28/workflows/e3433aea-52d7-40a5-b8cf-dc56eae0c353/jobs/30/artifacts)

**Comment by ardissaps** [comment]
@Einjerjar the link lead to this page, where can I download them? thanks

**Comment by Einjerjar** [comment]
mb, when the page loads, you should automatically be sent to the artifacts tab, under there you'll see a link that ends with 'build', clicking on that should download the file directly

**Comment by ardissaps** [comment]
> mb, when the page loads, you should automatically be sent to the artifacts tab, under there you'll see a link that ends with 'build', clicking on that should download the file directly

when I press the link, it only refresh this page (this github issue page)

edit : i figured it out, the link it self need to be copied the text, not clicked, launching the game now. thanks!

**Comment by Einjerjar** [comment]
I've edited the link, can you try again?

**Comment by ardissaps** [comment]
> I've edited the link, can you try again?

yes, the game launched, no crash, but when the keybind pressed, it only open the Keymap config screen, not the layout

**Comment by ardissaps** [comment]
Look like disabling "replace keybind screeen" does not work. it make if we open they keypap screen opened the config instead. Wish can use vanilla keybind screen on option screen, but open Keypam screen only with ` keybind.

**Comment by ardissaps** [comment]
@einjerjar, how about make make the ` directly open the layout? as the config we can already press setting on the layout or use mod menu. so we have both world be using vanilla keybind screen plus keymap screen

**Comment by Einjerjar** [comment]
I'm pretty sure pressing \` already does that, for the default minecraft keybinding screen, you can configure keymap to not override it, and show the default one via the settings button inside keymap, or via modmenu, in which case, you will be able to access the default keybinding screen via minecraft options, and keymap can then be access via \` or whatever button you set it to

**Comment by ardissaps** [comment]
> I'm pretty sure pressing \` already does that, for the default minecraft keybinding screen, you can configure keymap to not override it, and show the default one via the settings button inside keymap, or via modmenu, in which case, you will be able to access the default keybinding screen via minecraft options, and keymap can then be access via \` or whatever button you set it to

Yes in 1.18.2 fabric, but currently on quilt 1.19.2 with the link I download, the ~ open config instead, not layout, kind of bug

**Comment by SplendidAlakey** [comment]
In my case the game simply crashes when I click on the "open settings screen" with the beta build linked above: [removed, tag me if you need updated logs]

Other than that seems to work fine.

**Comment by Einjerjar** [comment]
@ardissaps ill try and look into it today on my free time

**Comment by Einjerjar** [comment]
@Footage2-Amply-Pounce i might have an idea why that happens, ill try looking into it today on my free time

**Comment by ardissaps** [comment]
No problem, take your time, no hurry :)

**Comment by Einjerjar** [comment]
looks like I won't be releasing a fix anytime soon, as far as my testing goes, cloth config (the current config mod I'm using), doesn't work well with quilt (due to a missing stub within qsl/quilted-fabric), so until that gets fixed, I cant really do much about it, in the meantime, I'm trying to make a new minimal config mod which should _hopefully_ work across launchers without much issue

**Comment by Einjerjar** [comment]
Hey there, so anyways, this one's good now, new internal config, no more need for cloth config, so it works perfectly now, I think (as far as testing went anyways), for 1.17.1, 1.18.2, and 1.19.2 version of quilt, didn't test on other similar versions tho (eg; 1.19,, 1.19.1)
