### ISSUE TITLE
[Quilt] Crash when opening Keymap controls on loader version 0.18.x

### ISSUE THREAD

**Issue by SplendidAlakey** [Einjerjar/keymap#29]
**MC** 1.19.2
**Quilt Loader** 0.18.1-beta.23
**QFAPI** 4.0.0-beta.24
**Keymap** 0.7.0-beta.0+1.19.2-fabric

To reproduce install the mod on Quilt Loader 0.18.1-beta.23, launch the game and click on "Keymap" button in settings. Loader 0.17.7 works without issues.

Logs: https://gist.github.com/SplendidAlakey/514ee26ac870c5aabe47481668b77476

**Comment by Einjerjar** [comment]
Will look into this, thanks!

**Comment by Einjerjar** [comment]
Seems like some breaking changes with how quilt 0.18.1 handles jar file systems, 

For the time being, the workaround mentioned over at https://github.com/QuiltMC/quilt-loader/issues/142#issuecomment-1334104456, works good on my end, add `-Dloader.workaround.jar_copied_mods=keymap` to your java lauch args, not sure how to handle multiple mods that use the workarounds tho, perhaps comma separate them?

In any case, will continue investigating till I can find a satisfactory solution, or wait till 0.18.1 gets stable, since they quilt team might have a better solution for a later date, thanks!

**Comment by SplendidAlakey** [comment]
Ah, yeah, I see. For the time being they've been adding erroring mods to the list of mods, that will be copied to a temp location first, so that it works out of the box. See: https://github.com/QuiltMC/quilt-loader/commit/b8d79bd5e23c0d335a04d53ae6cdc5e4658d1927, https://github.com/QuiltMC/quilt-loader/commit/233c57515ddc7dd91b164950a3fc17499cb4b336 and https://github.com/QuiltMC/quilt-loader/commit/15c9f3bea2c2268a8bcc78f69292b6b233554995. That last commit addresses specifically a server crash, which is not solved by the workaround, that works for clients, but since Keymap is a client-side mod, you can ignore it. Not sure, if a better solution is planned.

**Comment by Einjerjar** [comment]
Yeah, honestly don't think its a good solution tho, even if temporary, specially for some mods that don't really plan on officially supporting quilt, since the quilt team will then have to manually keep track of all erring mods, unless they can figure out how to automatically handle those.

That said, I just published a fix for the 1.19.2 version of keymap, is now up on modrinth and cf, hope it works on your end too 🍻

**Comment by SplendidAlakey** [comment]
Yep, it works. Thank you!
